version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: unless-stopped
    ports:
      - "8080:8080"  # Jenkins UI
      - "50000:50000"  # Jenkins agent
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
